//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PizzaAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class order_details
    {
        public long order_details_id { get; set; }
        public long order_id { get; set; }
        public string pizza_id { get; set; }
        public long quantity { get; set; }
    
        public virtual order order { get; set; }
        public virtual pizza pizza { get; set; }
    }
}
